#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/../.env"

echo "=== Lido Vault Monitor + Telegram Alert Demo (Track 7) ==="
echo ""

# Step 1: Fetch Lido stETH APR
echo "--- Step 1: Fetching Lido stETH APR ---"
APR_DATA=$(curl -s "https://eth-api.lido.fi/v1/protocol/steth/apr/sma")
APR=$(echo "$APR_DATA" | python3 -c "import json,sys; print(json.load(sys.stdin)['data']['smaApr'])")
echo "  stETH APR: ${APR}%"

# Step 2: Fetch Aave WETH supply rate from DefiLlama
echo -e "\n--- Step 2: Fetching Aave WETH supply rate ---"
AAVE_DATA=$(curl -s "https://yields.llama.fi/pools" 2>/dev/null || echo '{"data":[]}')
AAVE_RATE=$(echo "$AAVE_DATA" | python3 -c "
import json, sys
data = json.load(sys.stdin)
pools = data.get('data', [])
aave_weth = [p for p in pools if p.get('project') == 'aave-v3' and 'WETH' in p.get('symbol', '') and p.get('chain') == 'Ethereum']
if aave_weth:
    print(f'{aave_weth[0][\"apy\"]:.4f}')
else:
    print('2.1000')  # fallback
" 2>/dev/null || echo "2.1000")
echo "  Aave V3 WETH Supply Rate: ${AAVE_RATE}%"

# Step 3: Fetch withdrawal queue status
echo -e "\n--- Step 3: Checking withdrawal queue ---"
WQ_DATA=$(curl -s "https://eth-api.lido.fi/v1/protocol/withdrawals/status" 2>/dev/null || echo '{}')
WQ_INFO=$(echo "$WQ_DATA" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    unfinalized = data.get('data', {}).get('unfinalizedStETH', 'unknown')
    print(f'Unfinalized stETH: {unfinalized}')
except:
    print('Withdrawal queue data unavailable')
" 2>/dev/null || echo "Withdrawal queue data unavailable")
echo "  $WQ_INFO"

# Step 4: Fetch wstETH/stETH exchange rate
echo -e "\n--- Step 4: Checking wstETH exchange rate ---"
RATE_DATA=$(curl -s -X POST "https://eth.llamarpc.com" \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0","data":"0x035faf82"},"latest"],"id":1}')
RATE_HEX=$(echo "$RATE_DATA" | python3 -c "import json,sys; print(json.load(sys.stdin).get('result','0x0'))" 2>/dev/null || echo "0x0")
RATE_ETH=$(python3 -c "print(f'{int(\"$RATE_HEX\", 16) / 1e18:.6f}')" 2>/dev/null || echo "0")
echo "  wstETH/stETH rate: $RATE_ETH"

# Step 5: Generate alert report
echo -e "\n--- Step 5: Generating Alert Report ---"
python3 -c "
apr = float('$APR')
aave = float('$AAVE_RATE')
rate = float('$RATE_ETH')

alerts = []
baseline = 3.0

# Check APR vs Aave
if apr < aave:
    alerts.append(('WARNING', f'stETH APR ({apr:.2f}%) is BELOW Aave WETH rate ({aave:.2f}%)'))
elif apr < aave * 1.1:
    alerts.append(('INFO', f'stETH APR ({apr:.2f}%) is within 10% of Aave rate ({aave:.2f}%)'))

# Check APR deviation from baseline
if abs(apr - baseline) / baseline > 0.2:
    alerts.append(('WARNING', f'stETH APR deviation > 20% from {baseline}% baseline'))

# Check exchange rate
expected_rate = 1.18  # approximate expected range
if abs(rate - expected_rate) / expected_rate > 0.01:
    alerts.append(('INFO', f'wstETH rate ({rate:.6f}) deviating from expected ~{expected_rate}'))

# Format as Telegram alert
print('📊 *Lido Vault Health Report*')
print(f'')
print(f'*Metrics:*')
print(f'• stETH APR: {apr:.2f}%')
print(f'• Aave V3 WETH: {aave:.2f}%')
print(f'• wstETH Rate: {rate:.6f}')
print(f'')
if alerts:
    print(f'*Alerts ({len(alerts)}):*')
    for severity, msg in alerts:
        icon = '⚠️' if severity == 'WARNING' else 'ℹ️'
        print(f'{icon} [{severity}] {msg}')
else:
    print('✅ All metrics within normal range')
print(f'')
print(f'_Generated by Ottie Vault Monitor_')
"

echo -e "\n=== Vault Monitor Demo Complete ==="
